version: '2'
services:
  products-service:
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/admin/shop-products-api:20160930.1
    ports:
      - "5001:5001"
    environment: 
      - SHOP_PRODUCTS_API_PORT=5001
      - "constraint:node==jcoucp0-ucpnode"
  ratings-service:
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/admin/shop-ratings-api:20160930.1
    ports:
      - "5002:5002"
    environment:
      - SHOP_RATINGS_API_PORT=5002
      - "constraint:node==jcoucp0-ucpnode"
  recommandations-service:
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/admin/shop-recommandations-api:20160930.1
    ports:
      - "5003:5003"
    environment:
      - SHOP_RECOMMANDATIONS_API_PORT=5003
      - "constraint:node==jcoucp0-ucpnode"
  shop-front:
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/admin/shop-front:20160930.1
    ports:
      - "81:5004"
    environment:
      - SHOP_FRONT_PORT=5004
      - SHOP_PRODUCTS_API_URL=http://jconlbpiplabel.northeurope.cloudapp.azure.com:5001
      - SHOP_RATINGS_API_URL=http://jconlbpiplabel.northeurope.cloudapp.azure.com:5002
      - SHOP_RECOMMANDATIONS_API_URL=http://jconlbpiplabel.northeurope.cloudapp.azure.com:5003
      - "constraint:node==jcoucp0-ucpnode"