version: '2'
services:
  proxy:
    image: jcorioland/shop-nginx-proxy:latest
    ports: ["80:80"]
  products:
    image: jcorioland/shop-products-api:#{Build.BuildNumber}#
  ratings:
    image: jcorioland/shop-ratings-api:#{Build.BuildNumber}#
  recommandations:
    image: jcorioland/shop-recommandations-api:#{Build.BuildNumber}#
  shop:
    image: jcorioland/shop-front:#{Build.BuildNumber}#
    environment:
      - SHOP_PRODUCTS_API_URL=http://acsmyshop-agents.westeurope.cloudapp.azure.com/products/
      - SHOP_RATINGS_API_URL=http://acsmyshop-agents.westeurope.cloudapp.azure.com/ratings/
      - SHOP_RECOMMANDATIONS_API_URL=http://acsmyshop-agents.westeurope.cloudapp.azure.com/recommandations/