version: '2'

services:
  proxy:
    build: proxy
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/docker-datacenter/proxy:20161003
    ports: ["81:80"]

  shop:
    build: ShopFront
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/docker-datacenter/shop:20161003

  products:
    build: ProductsApi
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/docker-datacenter/products:20161003

  ratings:
    build: RatingsApi
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/docker-datacenter/ratings:20161003

  recommandations:
    build: RecommandationsApi
    image: jcodlbpiplabel.northeurope.cloudapp.azure.com/docker-datacenter/recommandations:20161003
