apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myshop-deployment
spec:
  minReadySeconds: 10
  template:
    metadata:
      labels: 
        name: myshop-deployment
        version: v0.3
    spec:
      containers:
      - name: proxy
        image: bhacr-microsoft.azurecr.io/shop/nginx-proxy:BuildNumber
        ports:
        - containerPort: 80
      - name: products
        image: bhacr-microsoft.azurecr.io/shop/products-api:BuildNumber
        ports:
        - containerPort: 5001
      - name: ratings
        image: bhacr-microsoft.azurecr.io/shop/ratings-api:BuildNumber
        ports:
        - containerPort: 5002
      - name: recommendations
        image: bhacr-microsoft.azurecr.io/shop/recommendations-api:BuildNumber
        ports:
        - containerPort: 5003
      - name: shop
        image: bhacr-microsoft.azurecr.io/shop/front:BuildNumber
        ports:
        - containerPort: 5000
      imagePullSecrets: 
        - name: bhacr