apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myshop-deployment
spec:
  minReadySeconds: 10
  template:
    metadata:
      labels: myshop-deployment
      version: v0.1
    spec:
      containers:
      - name: proxy
        image: bhacr-microsoft.azurecr.io/shop/nginx-proxy:latest
        ports:
          - containerPort: 80
      - name: products
        image: bhacr-microsoft.azurecr.io/shop/products-api:BuildNumber
      - name: ratings
        image: bhacr-microsoft.azurecr.io/shop/ratings-api:BuildNumber
      - name: recommendations
        image: bhacr-microsoft.azurecr.io/shop/recommendations-api:BuildNumber
      - name: shop
        image: bhacr-microsoft.azurecr.io/shop/front:BuildNumber
        env:
          - name: SHOP_PRODUCTS_API_URL
            value: http://bhk8s.westeurope.cloudapp.azure.com/products/
          - name: SHOP_RATINGS_API_URL
            value: http://bhk8s.westeurope.cloudapp.azure.com/ratings/
          - name: SHOP_RECOMMANDATIONS_API_URL
            value: http://bhk8s.westeurope.cloudapp.azure.com/recommendations/